import { User } from '../app/entities/user';
import { LoginTestData } from '../app/entities/loginTestData';
export const USUARIOS_TEST :LoginTestData[]= [
  {        
    "username":"avillucas+duenio1@gmail.com",
    "password":"1q2w3e4r5t6y"    
  },
  {        
    "username":"avillucas+supervisor1@gmail.com",
    "password":"1q2w3e4r5t6y"    
  },
  {
    "username":"avillucas+maitre1@gmail.com",
    "password":"1q2w3e4r5t6y",   
  },
  {
    "username":"avillucas+cocinero1@gmail.com",
    "password":"1q2w3e4r5t6y",   
  },
  {
    "username":"avillucas+bartender1@gmail.com",
    "password":"1q2w3e4r5t6y",   
  },
  {
    "username":"avillucas+mozo1@gmail.com",
    "password":"1q2w3e4r5t6y"    
  },  
  {
    "username":"avillucas+rechazado@gmail.com",
    "password":"1q2w3e4r5t6y"    
  },
  {
    "username":"avillucas+manycliente@gmail.com",
    "password":"1q2w3e4r5t6y"    
  },
  {
    "username":"avillucas+anonimo@gmail.com",
    "password":"1q2w3e4r5t6y"    
  },
];